import { useMemo, useState } from 'react'
import { ArrowRight, CheckCircle2, Clock3, Database, Link2, LockKeyhole, Search, ShieldAlert, UserRound, Workflow } from 'lucide-react'
import type { DatabaseLock, DatabaseLocks, DatabaseSession } from '@/entities/database-object'
import { Badge, EmptyState, Input, Select, WorkspacePanel } from '@/shared/ui'

type LocksPanelProps = {
  locks?: DatabaseLocks
  sessions?: DatabaseSession[]
  loading?: boolean
  source: 'mock' | 'api'
}

export function LocksPanel({ locks, sessions = [], loading, source }: LocksPanelProps) {
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('all')
  const [selectedId, setSelectedId] = useState('')
  const visible = useMemo(() => {
    const query = search.trim().toLowerCase()
    return (locks?.items ?? []).filter((lock) => (status === 'all' || (status === 'waiting' ? !lock.granted : lock.granted)) && (!query || `${lock.id} ${lock.type} ${lock.object} ${lock.mode} ${lock.query} ${lock.waitingPid} ${lock.blockingPid}`.toLowerCase().includes(query)))
  }, [locks?.items, search, status])
  const selected = visible.find((lock) => lock.id === selectedId) ?? visible[0]
  const waiting = (locks?.items ?? []).filter((lock) => !lock.granted)
  const blockingChainCount = locks?.blockingChains?.length ?? (source === 'mock' ? new Set(waiting.map((lock) => lock.waitingPid).filter(Boolean)).size : 0)

  function session(pid?: string) {
    return sessions.find((item) => item.id === pid)
  }

  if (loading) return <div className="grid min-h-80 place-items-center text-[length:var(--font-size-ui)] text-muted-foreground">Loading lock graph…</div>
  if (!locks?.available) return <EmptyState icon={<ShieldAlert />} title="Lock monitoring unavailable" description={locks?.message ?? 'The selected database role cannot inspect lock activity.'} />

  return <div className="space-y-4">
    <div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-border bg-surface p-4"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-lg bg-warning text-warning-foreground"><Clock3 className="size-4" /></span><Badge variant={waiting.length ? 'warning' : 'success'}>{waiting.length ? 'Attention' : 'Healthy'}</Badge></div><p className="mt-4 text-2xl font-semibold tabular-nums">{waiting.length}</p><p className="text-[length:var(--font-size-ui)] font-medium">Waiting locks</p><p className="mt-1 text-[length:var(--font-size-meta)] text-muted-foreground">Requests blocked by another transaction</p></div><div className="rounded-xl border border-border bg-surface p-4"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-lg bg-accent text-primary"><LockKeyhole className="size-4" /></span><Badge variant={source === 'mock' ? 'accent' : 'success'}>{source === 'mock' ? 'Sample locks' : 'Live adapter'}</Badge></div><p className="mt-4 text-2xl font-semibold tabular-nums">{locks.items.filter((lock) => lock.granted).length}</p><p className="text-[length:var(--font-size-ui)] font-medium">Granted locks</p><p className="mt-1 text-[length:var(--font-size-meta)] text-muted-foreground">Currently held lock records</p></div><div className="rounded-xl border border-border bg-surface p-4"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-lg bg-info text-info-foreground"><Workflow className="size-4" /></span><Badge variant={blockingChainCount ? 'warning' : 'success'}>{blockingChainCount ? 'Blocking' : 'Clear'}</Badge></div><p className="mt-4 text-2xl font-semibold tabular-nums">{blockingChainCount}</p><p className="text-[length:var(--font-size-ui)] font-medium">Blocking chains</p><p className="mt-1 text-[length:var(--font-size-meta)] text-muted-foreground">Waiter-to-blocker relationships reported by the adapter</p></div></div>
    {waiting.length ? <WorkspacePanel title="Blocking chains" description="Waiting session → blocking session relationships" actions={<Badge variant="warning"><ShieldAlert />{waiting.length} waiting</Badge>}><div className="grid gap-3 lg:grid-cols-2">{waiting.map((lock) => { const waiter = session(lock.waitingPid); const blocker = session(lock.blockingPid); return <button key={lock.id} type="button" aria-pressed={selected?.id === lock.id} onClick={() => setSelectedId(lock.id)} className="rounded-xl border border-border bg-background/55 p-3 text-left transition-colors hover:border-border-strong hover:bg-accent/30 focus-visible:ring-2 focus-visible:ring-primary aria-pressed:border-primary"><div className="grid grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] items-center gap-2"><div className="min-w-0 rounded-lg border border-warning/30 bg-warning/40 p-3"><div className="flex items-center gap-2"><Clock3 className="size-4 text-warning-foreground" /><span className="font-mono text-[length:var(--font-size-data)] font-semibold">PID {lock.waitingPid || '—'}</span></div><p className="mt-1 truncate text-[length:var(--font-size-meta)] text-muted-foreground">{waiter?.user || 'Waiting session'}</p></div><div className="grid place-items-center text-muted-foreground"><ArrowRight className="size-4" /><span className="mt-1 text-[10px] font-semibold uppercase">blocked by</span></div><div className="min-w-0 rounded-lg border border-destructive/25 bg-destructive/10 p-3"><div className="flex items-center gap-2"><ShieldAlert className="size-4 text-destructive" /><span className="font-mono text-[length:var(--font-size-data)] font-semibold">PID {lock.blockingPid || '—'}</span></div><p className="mt-1 truncate text-[length:var(--font-size-meta)] text-muted-foreground">{blocker?.user || 'Blocking session'}</p></div></div><div className="mt-3 flex items-center gap-2 text-[length:var(--font-size-meta)] text-muted-foreground"><Database className="size-3.5" /><span className="font-mono">{lock.object || lock.type}</span><span>·</span><span>{lock.mode || 'Unknown mode'}</span></div></button> })}</div></WorkspacePanel> : <WorkspacePanel><EmptyState compact icon={<CheckCircle2 />} title="No blocking chains" description="All lock requests are currently progressing without blockers." /></WorkspacePanel>}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(18rem,0.5fr)]">
      <WorkspacePanel noPadding title="Lock records" description={`${locks.items.length} catalog entries`}><div className="flex min-h-[var(--toolbar-height)] flex-wrap items-center gap-2 border-b border-border px-3 py-1.5"><div className="relative min-w-48 max-w-sm flex-1"><Search className="pointer-events-none absolute top-1/2 left-2.5 size-3.5 -translate-y-1/2 text-muted-foreground" /><Input aria-label="Search lock records" className="h-[var(--control-height-sm)] pl-8" value={search} placeholder="Object, mode, PID, or SQL" onChange={(event) => setSearch(event.target.value)} /></div><Select aria-label="Lock status" className="h-[var(--control-height-sm)] w-36" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All locks</option><option value="waiting">Waiting</option><option value="granted">Granted</option></Select></div>{visible.length ? <div className="overflow-auto"><table className="w-full min-w-[760px] border-collapse text-[length:var(--font-size-data)]"><thead><tr className="bg-grid-header text-left text-muted-foreground"><th className="border-b border-grid-line px-3 py-2 font-medium">Status</th><th className="border-b border-grid-line px-3 py-2 font-medium">Object</th><th className="border-b border-grid-line px-3 py-2 font-medium">Type</th><th className="border-b border-grid-line px-3 py-2 font-medium">Mode</th><th className="border-b border-grid-line px-3 py-2 font-medium">Waiting PID</th><th className="border-b border-grid-line px-3 py-2 font-medium">Blocking PID</th></tr></thead><tbody>{visible.map((lock) => <tr key={lock.id} tabIndex={0} aria-selected={selected?.id === lock.id} onClick={() => setSelectedId(lock.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelectedId(lock.id) } }} className="border-b border-grid-line outline-none hover:bg-accent/35 focus-visible:bg-accent/45 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary aria-selected:bg-accent/65"><td className="px-3 py-2.5"><Badge variant={lock.granted ? 'success' : 'warning'}>{lock.granted ? 'Granted' : 'Waiting'}</Badge></td><td className="px-3 py-2.5 font-mono font-medium text-foreground">{lock.object || '—'}</td><td className="px-3 py-2.5 text-muted-foreground">{lock.type}</td><td className="px-3 py-2.5 font-mono text-muted-foreground">{lock.mode || '—'}</td><td className="px-3 py-2.5 font-mono text-muted-foreground">{lock.waitingPid || '—'}</td><td className="px-3 py-2.5 font-mono text-muted-foreground">{lock.blockingPid || '—'}</td></tr>)}</tbody></table></div> : <EmptyState compact icon={<Search />} title="No locks match" description="Adjust the status filter or search text." />}</WorkspacePanel>
      <WorkspacePanel title={selected?.object || selected?.type || 'Lock details'} description={selected ? selected.id : 'Select a lock'}>{selected ? <div className="space-y-4"><div className="flex items-center justify-between"><Badge variant={selected.granted ? 'success' : 'warning'}>{selected.granted ? <CheckCircle2 /> : <Clock3 />}{selected.granted ? 'Granted' : 'Waiting'}</Badge><span className="font-mono text-[length:var(--font-size-meta)] text-muted-foreground">{selected.mode}</span></div><dl className="grid gap-3 text-[length:var(--font-size-ui)]"><div className="flex gap-3"><Database className="mt-0.5 size-4 text-muted-foreground" /><div><dt className="text-muted-foreground">Object</dt><dd className="font-mono text-foreground">{selected.object || 'Database-level'}</dd></div></div><div className="flex gap-3"><UserRound className="mt-0.5 size-4 text-muted-foreground" /><div><dt className="text-muted-foreground">Waiting session</dt><dd className="font-mono text-foreground">{selected.waitingPid || 'None'}</dd></div></div><div className="flex gap-3"><Link2 className="mt-0.5 size-4 text-muted-foreground" /><div><dt className="text-muted-foreground">Blocking session</dt><dd className="font-mono text-foreground">{selected.blockingPid || 'None'}</dd></div></div></dl><div><p className="text-[length:var(--font-size-meta)] font-medium text-muted-foreground">Statement</p><pre className="mt-2 max-h-40 overflow-auto rounded-lg border border-border bg-background/70 p-3 whitespace-pre-wrap font-mono text-[length:var(--font-size-data)] leading-5 text-foreground">{selected.query || 'Statement unavailable'}</pre></div></div> : <EmptyState compact title="No lock selected" />}</WorkspacePanel>
    </div>
  </div>
}
