import { useId, useMemo, useState } from 'react'
import { ArrowDown, ArrowUp, Asterisk, Braces, GripVertical, KeyRound, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import type { DatabaseEngine } from '@/entities/connection'
import type { TableColumn } from '@/entities/database-object'
import type { SchemaDraftAction, SchemaDraftChange } from '@/entities/schema'
import {
  Badge,
  Button,
  Checkbox,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  EmptyState,
  IconButton,
  Input,
  PropertyField,
  PropertyGrid,
  Select,
  Textarea,
  WorkspacePanel,
} from '@/shared/ui'

export type SchemaColumn = TableColumn & {
  id: string
  identity: boolean
  collation: string
}

type ColumnDraft = Omit<SchemaColumn, 'id'>

type ColumnsPanelProps = {
  columns: SchemaColumn[]
  engine: DatabaseEngine
  readOnly?: boolean
  onColumnsChange: (columns: SchemaColumn[]) => void
  onStage: (change: SchemaDraftChange) => void
}

const dataTypes: Record<'postgresql' | 'mysql', string[]> = {
  postgresql: ['uuid', 'varchar(255)', 'text', 'integer', 'bigint', 'numeric(12,2)', 'boolean', 'date', 'timestamp', 'timestamptz', 'jsonb'],
  mysql: ['char(36)', 'varchar(255)', 'text', 'int', 'bigint', 'decimal(12,2)', 'boolean', 'date', 'datetime', 'timestamp', 'json'],
}

const collations: Record<'postgresql' | 'mysql', Array<{ value: string; label: string }>> = {
  postgresql: [
    { value: 'database_default', label: 'Database default' },
    { value: 'en_US.utf8', label: 'en_US.utf8' },
    { value: 'C', label: 'C' },
    { value: 'POSIX', label: 'POSIX' },
  ],
  mysql: [
    { value: 'database_default', label: 'Database default' },
    { value: 'utf8mb4_0900_ai_ci', label: 'utf8mb4_0900_ai_ci' },
    { value: 'utf8mb4_unicode_ci', label: 'utf8mb4_unicode_ci' },
    { value: 'utf8mb4_bin', label: 'utf8mb4_bin' },
  ],
}

function dialect(engine: DatabaseEngine): 'postgresql' | 'mysql' {
  return engine === 'mysql' || engine === 'mariadb' ? 'mysql' : 'postgresql'
}

function sqlString(value: string) {
  return `'${value.replaceAll("'", "''")}'`
}

function blankColumn(): ColumnDraft {
  return {
    name: '',
    dataType: 'varchar(255)',
    nullable: true,
    defaultValue: null,
    comment: '',
    identity: false,
    collation: 'database_default',
  }
}

function columnDefinition(column: ColumnDraft, engine: DatabaseEngine) {
  const target = dialect(engine)
  const identity = column.identity ? target === 'postgresql' ? ' GENERATED BY DEFAULT AS IDENTITY' : ' AUTO_INCREMENT' : ''
  const nullable = column.nullable ? target === 'mysql' ? ' NULL' : '' : ' NOT NULL'
  const defaultValue = !column.identity && column.defaultValue?.trim() ? ` DEFAULT ${column.defaultValue.trim()}` : ''
  const collation = column.collation !== 'database_default' ? ` COLLATE ${target === 'postgresql' ? `"${column.collation.replaceAll('"', '""')}"` : column.collation}` : ''
  const comment = target === 'mysql' && column.comment.trim() ? ` COMMENT ${sqlString(column.comment.trim())}` : ''
  return `${column.dataType}${collation}${identity}${nullable}${defaultValue}${comment}`
}

function schemaDataType(column: ColumnDraft, engine: DatabaseEngine) {
  if (column.collation === 'database_default') return column.dataType
  return dialect(engine) === 'postgresql'
    ? `${column.dataType} COLLATE "${column.collation.replaceAll('"', '""')}"`
    : `${column.dataType} COLLATE ${column.collation}`
}

function schemaColumnDefinition(column: ColumnDraft, engine: DatabaseEngine) {
  const defaultValue = column.identity || !column.defaultValue?.trim() ? undefined : column.defaultValue.trim()
  return {
    name: column.name,
    dataType: schemaDataType(column, engine),
    nullable: column.identity ? false : column.nullable,
    defaultValue,
    comment: column.comment.trim(),
    identity: column.identity,
  }
}

function editColumnActions(previous: SchemaColumn, next: ColumnDraft, engine: DatabaseEngine): SchemaDraftAction[] {
  const actions: SchemaDraftAction[] = []
  const columnName = next.name
  if (previous.name !== next.name) actions.push({ kind: 'rename_column', name: previous.name, newName: next.name })
  if (previous.dataType !== next.dataType || previous.collation !== next.collation) actions.push({ kind: 'alter_column_type', name: columnName, dataType: schemaDataType(next, engine) })
  if (previous.nullable !== next.nullable) actions.push({ kind: 'set_column_nullable', name: columnName, nullable: next.nullable })
  const previousDefault = previous.defaultValue?.trim() || null
  const nextDefault = next.defaultValue?.trim() || null
  if (previousDefault !== nextDefault) actions.push({ kind: 'set_column_default', name: columnName, defaultValue: nextDefault })
  if (previous.comment !== next.comment) actions.push({ kind: 'set_column_comment', name: columnName, comment: next.comment.trim() })
  return actions
}

function ColumnDialog({
  open,
  column,
  engine,
  mode,
  onOpenChange,
  onSubmit,
}: {
  open: boolean
  column: ColumnDraft
  engine: DatabaseEngine
  mode: 'add' | 'edit'
  onOpenChange: (open: boolean) => void
  onSubmit: (column: ColumnDraft) => void
}) {
  const [draft, setDraft] = useState(column)
  const nameError = draft.name.trim() ? '' : 'Column name is required.'
  const targetDialect = dialect(engine)
  const generatedId = useId().replaceAll(':', '')
  const fieldId = `schema-column-${generatedId}`
  const identityLabel = targetDialect === 'postgresql' ? 'Generated identity' : 'Auto increment'

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>{mode === 'add' ? 'Add column' : `Edit ${column.name}`}</DialogTitle>
          <DialogDescription>Configure the column definition. The change is staged and no database object is modified yet.</DialogDescription>
        </DialogHeader>
        <PropertyGrid>
          <PropertyField label="Name" htmlFor={`${fieldId}-name`} required error={nameError ? <span id={`${fieldId}-name-error`}>{nameError}</span> : undefined}>
            <Input id={`${fieldId}-name`} aria-label="Name" aria-describedby={nameError ? `${fieldId}-name-error` : undefined} autoFocus required invalid={Boolean(nameError)} value={draft.name} onChange={(event) => setDraft((value) => ({ ...value, name: event.target.value }))} />
          </PropertyField>
          <PropertyField label="Data type" htmlFor={`${fieldId}-data-type`} required>
            <Select id={`${fieldId}-data-type`} aria-label="Data type" required value={draft.dataType} onChange={(event) => setDraft((value) => ({ ...value, dataType: event.target.value }))}>
              {dataTypes[targetDialect].map((dataType) => <option key={dataType} value={dataType}>{dataType}</option>)}
            </Select>
          </PropertyField>
          <PropertyField label="Default value" htmlFor={`${fieldId}-default`} description={<span id={`${fieldId}-default-description`}>Enter a SQL expression, for example now() or false.</span>}>
            <Input id={`${fieldId}-default`} aria-label="Default value" aria-describedby={`${fieldId}-default-description`} className="font-mono" disabled={draft.identity} value={draft.defaultValue ?? ''} placeholder={draft.identity ? 'Identity columns generate their value' : 'No default'} onChange={(event) => setDraft((value) => ({ ...value, defaultValue: event.target.value || null }))} />
          </PropertyField>
          <PropertyField label="Collation" htmlFor={`${fieldId}-collation`}>
            <Select id={`${fieldId}-collation`} aria-label="Collation" value={draft.collation} onChange={(event) => setDraft((value) => ({ ...value, collation: event.target.value }))}>
              {collations[targetDialect].map((collation) => <option key={collation.value} value={collation.value}>{collation.label}</option>)}
            </Select>
          </PropertyField>
        </PropertyGrid>
        <div className="grid gap-3 rounded-lg border border-border bg-muted/35 p-3 sm:grid-cols-2">
          <Checkbox id={`${fieldId}-nullable`} aria-label="Allow NULL values" checked={draft.nullable} label="Allow NULL values" onChange={(event) => setDraft((value) => ({ ...value, nullable: event.target.checked }))} />
          <Checkbox id={`${fieldId}-identity`} aria-label={identityLabel} disabled={mode === 'edit'} checked={draft.identity} label={identityLabel} onChange={(event) => setDraft((value) => ({ ...value, identity: event.target.checked, nullable: event.target.checked ? false : value.nullable, defaultValue: event.target.checked ? null : value.defaultValue }))} />
        </div>
        <PropertyField label="Comment" htmlFor={`${fieldId}-comment`}>
          <Textarea id={`${fieldId}-comment`} aria-label="Comment" value={draft.comment} placeholder="Describe how this column is used" onChange={(event) => setDraft((value) => ({ ...value, comment: event.target.value }))} />
        </PropertyField>
        <div className="rounded-lg border border-border bg-background/70 px-3 py-2.5">
          <p className="text-[length:var(--font-size-meta)] font-medium text-muted-foreground">Definition preview</p>
          <code className="mt-1 block overflow-x-auto whitespace-nowrap text-[length:var(--font-size-data)] text-foreground">{draft.name || 'column_name'} {columnDefinition(draft, engine)}</code>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button disabled={Boolean(nameError)} onClick={() => onSubmit({ ...draft, name: draft.name.trim() })}>{mode === 'add' ? 'Stage column' : 'Stage changes'}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

export function ColumnsPanel({ columns, engine, readOnly, onColumnsChange, onStage }: ColumnsPanelProps) {
  const [search, setSearch] = useState('')
  const [selectedId, setSelectedId] = useState(columns[0]?.id ?? '')
  const [dialog, setDialog] = useState<{ mode: 'add' | 'edit'; draft: ColumnDraft }>()
  const [deleteId, setDeleteId] = useState<string>()
  const filteredColumns = useMemo(() => {
    const query = search.trim().toLowerCase()
    return columns.filter((column) => !query || `${column.name} ${column.dataType} ${column.comment}`.toLowerCase().includes(query))
  }, [columns, search])
  const selected = filteredColumns.find((column) => column.id === selectedId) ?? filteredColumns[0]
  const deleteColumn = columns.find((column) => column.id === deleteId)

  function moveColumn(id: string, direction: -1 | 1) {
    const index = columns.findIndex((column) => column.id === id)
    const target = index + direction
    if (index < 0 || target < 0 || target >= columns.length) return
    const next = [...columns]
    const [column] = next.splice(index, 1)
    next.splice(target, 0, column)
    onColumnsChange(next)
  }

  function submitColumn(draft: ColumnDraft) {
    if (dialog?.mode === 'add') {
      const id = `column-${Date.now()}`
      onColumnsChange([...columns, { ...draft, id }])
      setSelectedId(id)
      onStage({
        label: `Add ${draft.name}`,
        description: `${draft.dataType}${draft.nullable ? '' : ' · required'}`,
        actions: [{ kind: 'add_column', column: schemaColumnDefinition(draft, engine) }],
      })
    } else if (selected) {
      const previousName = selected.name
      const actions = editColumnActions(selected, draft, engine)
      onColumnsChange(columns.map((column) => column.id === selected.id ? { ...draft, id: selected.id } : column))
      if (actions.length) onStage({
        label: `Alter ${previousName}`,
        description: `${draft.name} · ${draft.dataType}`,
        actions,
      })
    }
    setDialog(undefined)
  }

  function confirmDelete() {
    if (!deleteColumn) return
    const next = columns.filter((column) => column.id !== deleteColumn.id)
    onColumnsChange(next)
    setSelectedId(next[0]?.id ?? '')
    onStage({ label: `Drop ${deleteColumn.name}`, description: 'Destructive column change', actions: [{ kind: 'drop_column', name: deleteColumn.name, cascade: false }] })
    setDeleteId(undefined)
  }

  return (
    <div className="grid min-h-0 flex-1 grid-cols-[minmax(0,1.7fr)_minmax(15rem,0.7fr)] gap-4 max-xl:grid-cols-1">
      <WorkspacePanel noPadding title="Columns" description={`${columns.length} definitions · select a row to inspect`} actions={<Button size="xs" disabled={readOnly} onClick={() => setDialog({ mode: 'add', draft: blankColumn() })}><Plus />Add column</Button>}>
        <div className="flex min-h-[var(--toolbar-height)] items-center gap-2 border-b border-border px-3 py-1.5">
          <div className="relative min-w-48 flex-1 max-w-sm">
            <Search className="pointer-events-none absolute top-1/2 left-2.5 size-3.5 -translate-y-1/2 text-muted-foreground" />
            <Input className="h-[var(--control-height-sm)] pl-8" value={search} placeholder="Find a column" onChange={(event) => setSearch(event.target.value)} />
          </div>
          <Badge variant="outline">{filteredColumns.length} shown</Badge>
        </div>
        {filteredColumns.length ? (
          <div className="overflow-auto">
            <table className="w-full min-w-[760px] border-collapse text-[length:var(--font-size-data)]">
              <thead><tr className="bg-grid-header text-left text-muted-foreground"><th className="w-10 border-b border-grid-line px-2 py-2"><span className="sr-only">Order</span></th><th className="border-b border-grid-line px-3 py-2 font-medium">Column</th><th className="border-b border-grid-line px-3 py-2 font-medium">Type</th><th className="border-b border-grid-line px-3 py-2 font-medium">Nullable</th><th className="border-b border-grid-line px-3 py-2 font-medium">Default</th><th className="w-32 border-b border-grid-line px-3 py-2"><span className="sr-only">Actions</span></th></tr></thead>
              <tbody>
                {filteredColumns.map((column) => {
                  const index = columns.findIndex((item) => item.id === column.id)
                  return (
                    <tr key={column.id} tabIndex={0} aria-selected={column.id === selected?.id} onClick={() => setSelectedId(column.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelectedId(column.id) } }} className="group border-b border-grid-line outline-none hover:bg-accent/35 focus-visible:bg-accent/45 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary aria-selected:bg-accent/65">
                      <td className="px-2 py-2 text-muted-foreground"><GripVertical className="size-3.5" /></td>
                      <td className="px-3 py-2"><span className="flex items-center gap-2 font-mono font-medium text-foreground">{index === 0 ? <KeyRound className="size-3.5 text-amber-400" /> : <Braces className="size-3.5 text-primary" />}{column.name}</span></td>
                      <td className="px-3 py-2"><Badge variant="outline" className="rounded-md font-mono font-normal">{column.dataType}</Badge></td>
                      <td className="px-3 py-2 text-muted-foreground">{column.nullable ? 'Yes' : 'No'}</td>
                      <td className="max-w-52 truncate px-3 py-2 font-mono text-muted-foreground">{column.defaultValue || '—'}</td>
                      <td className="px-3 py-1.5"><div className="flex justify-end gap-0.5 opacity-70 group-hover:opacity-100"><IconButton label={`Move ${column.name} up`} size="icon-xs" disabled={readOnly || index === 0} onClick={(event) => { event.stopPropagation(); moveColumn(column.id, -1) }}><ArrowUp /></IconButton><IconButton label={`Move ${column.name} down`} size="icon-xs" disabled={readOnly || index === columns.length - 1} onClick={(event) => { event.stopPropagation(); moveColumn(column.id, 1) }}><ArrowDown /></IconButton><IconButton label={`Edit ${column.name}`} size="icon-xs" disabled={readOnly} onClick={(event) => { event.stopPropagation(); setSelectedId(column.id); setDialog({ mode: 'edit', draft: { ...column } }) }}><Pencil /></IconButton><IconButton label={`Drop ${column.name}`} size="icon-xs" variant="ghost" className="hover:text-destructive" disabled={readOnly} onClick={(event) => { event.stopPropagation(); setDeleteId(column.id) }}><Trash2 /></IconButton></div></td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        ) : <EmptyState compact icon={<Search />} title="No matching columns" description="Try a column name, type, or comment." />}
      </WorkspacePanel>

      <WorkspacePanel title={selected?.name ?? 'Column details'} description={selected ? `Position ${columns.findIndex((column) => column.id === selected.id) + 1} of ${columns.length}` : 'Select a column'}>
        {selected ? <div className="space-y-5">
          <div className="flex items-center gap-2"><Badge variant="accent" className="rounded-md font-mono">{selected.dataType}</Badge>{selected.nullable ? <Badge variant="outline">Nullable</Badge> : <Badge variant="warning"><Asterisk />Required</Badge>}{selected.identity ? <Badge variant="info">Identity</Badge> : null}</div>
          <dl className="grid gap-3 text-[length:var(--font-size-ui)]">
            <div className="grid gap-1"><dt className="text-muted-foreground">Default</dt><dd className="rounded-md border border-border bg-background/70 px-2.5 py-2 font-mono text-[length:var(--font-size-data)]">{selected.defaultValue || 'No default'}</dd></div>
            <div className="grid gap-1"><dt className="text-muted-foreground">Collation</dt><dd className="font-mono text-[length:var(--font-size-data)]">{selected.collation}</dd></div>
            <div className="grid gap-1"><dt className="text-muted-foreground">Comment</dt><dd className="leading-5 text-foreground">{selected.comment || 'No documentation yet.'}</dd></div>
          </dl>
          <Button className="w-full" size="sm" variant="outline" disabled={readOnly} onClick={() => setDialog({ mode: 'edit', draft: { ...selected } })}><Pencil />Edit definition</Button>
        </div> : <EmptyState compact title="No column selected" />}
      </WorkspacePanel>

      {dialog ? <ColumnDialog key={`${dialog.mode}:${dialog.draft.name}`} open column={dialog.draft} engine={engine} mode={dialog.mode} onOpenChange={(open) => { if (!open) setDialog(undefined) }} onSubmit={submitColumn} /> : null}
      <Dialog open={Boolean(deleteColumn)} onOpenChange={(open) => { if (!open) setDeleteId(undefined) }}>
        <DialogContent>
          <DialogHeader><DialogTitle>Drop column {deleteColumn?.name}?</DialogTitle><DialogDescription>This stages a destructive preview. Existing values, indexes, and dependent objects would be removed if the SQL is executed later.</DialogDescription></DialogHeader>
          <div className="rounded-lg border border-destructive/25 bg-destructive/10 px-3 py-2.5 font-mono text-[length:var(--font-size-data)] text-destructive">ALTER TABLE {'{{table}}'} DROP COLUMN {deleteColumn?.name};</div>
          <DialogFooter><Button variant="outline" onClick={() => setDeleteId(undefined)}>Keep column</Button><Button variant="destructive" onClick={confirmDelete}><Trash2 />Stage drop</Button></DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
